CXXFLAGS := -std=c++20 -Werror -Wall -Wpedantic -Wconversion

#stuff.o: stuff.cpp	
#	g++  $(CXXFLAGS) -c stuff.cpp

.FORCE:

kodu14: kodu14.cpp .FORCE
	g++  $(CXXFLAGS) -o kodu14 kodu14.cpp 
	./kodu14