CXXFLAGS := -std=c++20 -Werror -Wall -Wpedantic -Wconversion

alfalt.o: alfalt.cpp	
	g++  $(CXXFLAGS) -c alfalt.cpp

.FORCE:

praks8: praks8.cpp .FORCE
	g++  $(CXXFLAGS) -o praks8 praks8.cpp
	./praks8