CXXFLAGS := -std=c++20 -Werror -Wall -Wpedantic -Wconversion

#stuff.o: stuff.cpp	
#	g++  $(CXXFLAGS) -c stuff.cpp

.FORCE:

kodu13: kodu13.cpp .FORCE
	g++  $(CXXFLAGS) -o kodu13 kodu13.cpp 
	./kodu13