CXXFLAGS := -std=c++20 -Werror -Wall -Wpedantic -Wconversion

#stuff.o: stuff.cpp	
#	g++  $(CXXFLAGS) -c stuff.cpp

.FORCE:

prax14: prax14.cpp .FORCE
	g++  $(CXXFLAGS) -o prax14 prax14.cpp 
	./prax14