CXXFLAGS := -std=c++20 -Werror -Wall -Wpedantic -Wconversion

#stuff.o: stuff.cpp	
#	g++  $(CXXFLAGS) -c stuff.cpp

.FORCE:

prax13: prax13.cpp .FORCE
	g++  $(CXXFLAGS) -o prax13 prax13.cpp 
	./prax13