CXXFLAGS := -std=c++20 -Werror -Wall -Wpedantic -Wconversion
#PahupidiArv.o: PahupidiArv.cpp	
#	g++  $(CXXFLAGS) -c PahupidiArv.cpp

.FORCE:

KT: KT.cpp  .FORCE
	g++  $(CXXFLAGS) -o KT Kt.cpp 
	./KT 71.2 1.81